[package]
name = "yt-api-videosum"
version = "0.1.1"
authors = ["Zoltan Kovari"]
repository = "https://github.com/zkoevaari/yt-api-videosum.git"
license = "Apache-2.0"
edition = "2021"

[dependencies]
chrono = "0.4"
http = "1.1"
serde_json = "1.0"
ureq = { version="2.10", features=["json"] }
